// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjPuR-_d-b-gsafn-p_3329yItoTV7yms',
    appId: '1:201333865051:web:0a0fe1c7b0148a965d1d7e',
    messagingSenderId: '201333865051',
    projectId: 'hyacom-b97f7',
    authDomain: 'hyacom-b97f7.firebaseapp.com',
    storageBucket: 'hyacom-b97f7.firebasestorage.app',
    measurementId: 'G-VN8LMVPE17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsBbNf52IQTToxSl-c-ERWwNx5np6Y1oY',
    appId: '1:201333865051:android:16468fa47dd904765d1d7e',
    messagingSenderId: '201333865051',
    projectId: 'hyacom-b97f7',
    storageBucket: 'hyacom-b97f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCImrkHGDRxp1AJY6HF93hbnlM_bpqtKKw',
    appId: '1:201333865051:ios:cd37e9190a9bec0f5d1d7e',
    messagingSenderId: '201333865051',
    projectId: 'hyacom-b97f7',
    storageBucket: 'hyacom-b97f7.firebasestorage.app',
    iosBundleId: 'com.example.hayacom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCImrkHGDRxp1AJY6HF93hbnlM_bpqtKKw',
    appId: '1:201333865051:ios:cd37e9190a9bec0f5d1d7e',
    messagingSenderId: '201333865051',
    projectId: 'hyacom-b97f7',
    storageBucket: 'hyacom-b97f7.firebasestorage.app',
    iosBundleId: 'com.example.hayacom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjPuR-_d-b-gsafn-p_3329yItoTV7yms',
    appId: '1:201333865051:web:09b7b30af898d6505d1d7e',
    messagingSenderId: '201333865051',
    projectId: 'hyacom-b97f7',
    authDomain: 'hyacom-b97f7.firebaseapp.com',
    storageBucket: 'hyacom-b97f7.firebasestorage.app',
    measurementId: 'G-SZMYZELZBX',
  );
}
